### PR TITLE
BROKERS: POST Audio File

### LINKED ISSUE #210: BROKERS: POST Audio File
# The Ask
We need to develop an OpenAI Broker Method that POST Audio files and gets back transcriptions of these files

# How to Complete this Task
Here's some steps to complete this deliverable.

- Ensure that you understand how to natively talk to OpenAI API using Postman - (includes account & API key)
- Find the reference to integrating with OpenAI APIs [here](https://platform.openai.com/docs/api-reference/audio/create)
- Learn what Brokers are [here](https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md#1-brokers)
- Watch how The Standard Community developed a similar Broker for OpenAI [here](https://www.youtube.com/watch?v=YRLymNBSlqI&list=PLan3SCnsISTTl_MnGP6B78Nfu9Ix8G4mU&index=11)
- If you have any questions - ask The Standard Community [here](https://discord.com/invite/vdPZ7hS52X)

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

### PR DESCRIPTION
**Pull request by Catalin-Andronie**
Closes #210

### CODE REVIEW

**Comment by mabroukmahdhi** [comment]
@Catalin-Andronie Please fix the PR's name

**Comment by Catalin-Andronie** [comment]
> @Catalin-Andronie Please fix the PR's name

@mabroukmahdhi  good catch, thanks

**Comment by Catalin-Andronie** [comment]
@mabroukmahdhi @hassanhabib One thing to be mentioned here is that I did not add the "response_format" option on the `ExternalAudioTranscriptionRequest` model, since that changes the response type that we are receiving. At the moment the format of the transcript output is defaulted to `json` and can have one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`. We need to find a good way to overload the `OpenAIBroker.PostAudioTranscriptionRequestAsync()` method since we cannot simply overload by the method return type.

I suggest tackling this as another issue.
Let me know if you want me to add that issue.

**Comment by hassanhabib** [comment]
> @mabroukmahdhi @hassanhabib One thing to be mentioned here is that I did not add the "response_format" option on the `ExternalAudioTranscriptionRequest` model, since that changes the response type that we are receiving. At the moment the format of the transcript output is defaulted to `json` and can have one of these options: `json`, `text`, `srt`, `verbose_json`, or `vtt`. We need to find a good way to overload the `OpenAIBroker.PostAudioTranscriptionRequestAsync()` method since we cannot simply overload by the method return type.
> 
> I suggest tackling this as another issue. Let me know if you want me to add that issue.

@Catalin-Andronie in this case we are going to need multiple Foundation Service methods and one Processing Service to give out these options.

**Pull request merged**
