### PR TITLE
CODE RUB: FineTuneClientServiceException Class Update v2.10.1

### PR DESCRIPTION
**Pull request by Lezune**
Updated FineTuneClientServiceException class by removing constructors in which the error message was hard coded in. Updated all relevant service files to include message.

### CODE REVIEW

**Review by glhays — CHANGES_REQUESTED** [review]
InComplete Localize and Categorize

**Comment by Lezune** [comment]
> InComplete Localize and Categorize

Hello @glhays,

I am not entirely sure what you are referring to in regards to your comment. Would it be possible to clarify the issue? 

To go over the changes I made, I removed one of the constructors. This was due to the fact that the string being provided to its base class was no longer being provided internally since the string was being passed when we create the object. We would then need to add a string variable to the incoming parameters. This would then result in both constructors being exactly the same. Thus we removed the 1st constructor. 

All files that used the deleted constructor in the object creation of the Exception were then refactored to include the string message that was initially hardcoded into the Exception class.

**Comment by glhays** [comment]
> > InComplete Localize and Categorize
> 
> Hello @glhays,
> 
> I am not entirely sure what you are referring to in regards to your comment. Would it be possible to clarify the issue?
> 
> To go over the changes I made, I removed one of the constructors. This was due to the fact that the string being provided to its base class was no longer being provided internally since the string was being passed when we create the object. We would then need to add a string variable to the incoming parameters. This would then result in both constructors being exactly the same. Thus we removed the 1st constructor.
> 
> All files that used the deleted constructor in the object creation of the Exception were then refactored to include the string message that was initially hardcoded into the Exception class.
image

**Comment by glhays** [comment]
> > InComplete Localize and Categorize
> 
> Hello @glhays,
> 
> I am not entirely sure what you are referring to in regards to your comment. Would it be possible to clarify the issue?
> 
> To go over the changes I made, I removed one of the constructors. This was due to the fact that the string being provided to its base class was no longer being provided internally since the string was being passed when we create the object. We would then need to add a string variable to the incoming parameters. This would then result in both constructors being exactly the same. Thus we removed the 1st constructor.
> 
> All files that used the deleted constructor in the object creation of the Exception were then refactored to include the string message that was initially hardcoded into the Exception class.

Disregard my comment here in the wrong review. Sorry.

**Comment by glhays** [comment]
> > InComplete Localize and Categorize
> 
> Hello @glhays,
> 
> I am not entirely sure what you are referring to in regards to your comment. Would it be possible to clarify the issue?
> 
> To go over the changes I made, I removed one of the constructors. This was due to the fact that the string being provided to its base class was no longer being provided internally since the string was being passed when we create the object. We would then need to add a string variable to the incoming parameters. This would then result in both constructors being exactly the same. Thus we removed the 1st constructor.
> 
> All files that used the deleted constructor in the object creation of the Exception were then refactored to include the string message that was initially hardcoded into the Exception class.

You need to localize the Exception then Categorize it as in this sample of ADOTNet
image

**Comment by Lezune** [comment]
@glhays 

Is this what you wanted? Also, going forward, do you want me to add a create method for every exception regardless if the exception is used one or multiple times?

**Comment by glhays** [comment]
> @glhays
> 
> Is this what you wanted? Also, going forward, do you want me to add a create method for every exception regardless if the exception is used once or multiple times?

Don't take it so literal, my original point was directed at multiple messages of the same string value can be called from the same Create message to eliminate repeated strings. That is all as far as that goes.
You need to follow the upgrade path as it is and has been done in the other repositories like ADotNet, LeVent and a couple others. If it need be yes there may be a CreateSomeValidationException(sample) for the Exceptions and in Validations there may be just a Throw with a message. I can not tell you just go do this, you need to understand it as well. That takes some learning. Once you see the pattern, yes you may have alot more work ahead of you other than just moving the messages from the Exceptions classes to the Throw routine in the TryCatch pattern.

Let's think of it this way
V2.10.0 added the exception messages to the unit tests preventing some one from changing it in a said model exception class where it lived. If it was the test will break and then a system exposes it via a failing test. Having the messages in the models breaks the rule of models should be anemic and do not carry data or logic per The-Standard.
V2.10.1 moves the messages to the Service layers Exceptions and Validations to make the models adhere to the Anemic rule for models.
See the release notes for [V2.10.1](https://github.com/hassanhabib/The-Standard/releases)

**Comment by glhays** [comment]
@Lezune 
The circled red Service Exception is this PR.
The green X will be the same implementation, there are 4 catches calling the same FineTuneDependencyException so you need one CreateFineTuneDependencyException. Then one for the FineTuneDependencyValidationException so one CreateFineTuneDependencyValidationException for the blue.
Remember to pass in the appropriate caught errors.

Also remember that your Create methods should follow the order of the catch orders 
1. CreateFineTuneDependencyException
2. CreateFineTuneDependencyValidationException 
3. CreateFineTuneServiceException

I am not sure why you broke these PR's out the way you have?

image

**Comment by glhays** [comment]
@Lezune On line 84 of the image above is incorrect should be a call to the CreateFineTuneServiceException maybe you caught my error. Got interrupted and my train of thought.

Here is what it should be.
image

**Comment by Lezune** [comment]
Thank you for providing that information and images. That has definitely added clarity to any confusion I was having. I currently am being pulled away for other work but I will update things as soon as I am free. Also, if you would like, I can merge the Client-FineTunes files into one pull request and add the changes all together. I know we have added correspondance and changes in this pull request but i can provide links in a comment. It seems to make sense to combine these changes together but it is whatever you prefer or think is best.

**Comment by glhays** [comment]
> Thank you for providing that information and images. That has definitely added clarity to any confusion I was having. I currently am being pulled away for other work but I will update things as soon as I am free. Also, if you would like, I can merge the Client-FineTunes files into one pull request and add the changes all together. I know we have added correspondance and changes in this pull request but i can provide links in a comment. It seems to make sense to combine these changes together but it is whatever you prefer or think is best.

I found in my upgrades it is easier to do them by Service layer, so you are working in one set of files Models/Service/Tests. So all FineTunes in one PR and so forth. I am not concerned with establishing a record on the comments and such. Not that big of a deal. I think it would be a lot easier to manage what your committing and for reviewing if they were all together. I also think it may eliminate possible conflicts when merging and someone else pushes changes on you.

**Comment by Lezune** [comment]
Closing Pull Request. Resolving in PR #548.

**Pull request closed without merging**
