### PR TITLE
CODE RUB: Replace Hardcoded Values with Constants

### LINKED ISSUE #186: CODE RUB: Replace `application/json` and `Bearer` with Strongly Typed Values
Assigning this to @tekprofessional

### PR DESCRIPTION
**Pull request by tekprofessional**
Closes #186 

Also added strongly typed value for Encoding.UTF8.WebName

### CODE REVIEW

**Comment by BrianLParker** [comment]
@hassanhabib @tekprofessional @ElbekDeveloper @mabroukmahdhi 
Do we do not want a 162kb dependency for this?
This PR is bringing in Microsoft.AspNetCore.Authentication.JwtBearer

I would suggest:
Remove the library and create local constants.
Rename the PR to
`CODE RUB: Replace Hardcoded Values with Constants`

**Comment by hassanhabib** [comment]
@tekprofessional read the contribution rules for this repo. PRs must follow certain conventions to be eligible for a merge.

**Comment by tekprofessional** [comment]
> @hassanhabib @tekprofessional @ElbekDeveloper @mabroukmahdhi Do we want a 162kb dependency for this? This PR is bringing in Microsoft.AspNetCore.Authentication.JwtBearer
> 
> I would suggest: Remove the library and create local constants. Rename the PR to `CODE RUB: Replace Hardcoded Values with Constants` it is still showing `Users/tekprofessional/coderub replace hardcoded values with constants` above.

Thanks Brian. Renamed.  Interested in hearing other's input.  162k does seem rather large for just a strongly typed string.

**Comment by hassanhabib** [comment]
I agree with @BrianLParker its not worth a whole library.
Shutting this down.

**Pull request closed without merging**
