### PR TITLE
CODE RUB: LocalFiles Exceptions Upgrade V2.10.0

### PR DESCRIPTION
**Pull request by sammy-timalsina**
Closes: #418

### CODE REVIEW

**Comment by glhays** [comment]
@sammy-timalsina Please fix your PR name to align with The Standard.
Also please place where it says " No description provided" at the top here the
Closes: #
place the issue number or select it from the drop down.

**Comment by sammy-timalsina** [comment]
> @sammy-timalsina Please fix your PR name to align with The Standard. Also please place where it says " No description provided" at the top here the Closes: # place the issue number or select it from the drop down after the #.

@glhays Sorry, this is my first time contributing to OS.

**Comment by glhays** [comment]
> > @sammy-timalsina Please fix your PR name to align with The Standard. Also please place where it says " No description provided" at the top here the Closes: # place the issue number or select it from the drop down after the #.
> 
> @glhays Sorry, this is my first time contributing to OS.

Yep I know the feeling. PR name needs fixed as well see the image. 
You can review [here](https://github.com/hassanhabib/The-Standard-Team)on Standard guidelines for branching, naming, and such.

image

**Comment by glhays** [comment]
@sammy-timalsina Are you still working on the LocalFiles Tests upgrade?
image

**Comment by sammy-timalsina** [comment]
> @sammy-timalsina Are you still working on the LocalFiles Tests upgrade? image

@glhays I worked on both. But had problem when committing all the changes, for some reasons it shows two commits. Do we need to delete this PR and start over again? 
image

**Comment by glhays** [comment]
@sammy-timalsina I only see 4 files. You can close this PR if you elect to, you can not delete it.
image

**Comment by sammy-timalsina** [comment]
> @sammy-timalsina I only see 4 files. You can close this PR if you elect to, you can not delete it. image

Hey @glhays , Apologies, I am learning the process of how you guys do it. Thanks for your guidance, I appreciate it.

**Comment by glhays** [comment]
@sammy-timalsina resolve the comments

**Comment by glhays** [comment]
@sammy-timalsina you also have not verified your account. We require that you do.
Watch this video [here](https://www.youtube.com/watch?v=u9L5kDlU8rs&t=407s) and more info available in the description on a common issue some may have. Follow the path closely step by step.

**Comment by sammy-timalsina** [comment]
> @sammy-timalsina you also have not verified your account. We require that you do. Watch this video [here](https://www.youtube.com/watch?v=u9L5kDlU8rs&t=407s) and more info available in the description on a common issue some may have. Follow the path closely step by step. Also if your not already on the [Discord](https://discord.gg/K36q4yQg) channel, your welcome to ask for assistance.

Thanks I verified my account, did not know I have to verify it before the commit. thanks again.

**Comment by sammy-timalsina** [comment]
> @sammy-timalsina you also have not verified your account. We require that you do. Watch this video [here](https://www.youtube.com/watch?v=u9L5kDlU8rs&t=407s) and more info available in the description on a common issue some may have. Follow the path closely step by step. Also if your not already on the [Discord](https://discord.gg/K36q4yQg) channel, your welcome to ask for assistance.

Perfect, I will make sure I am on discord!

**Review by glhays — APPROVED** [review]

**Pull request merged**
