### PR TITLE
INFRA: Improve Automation Process

### LINKED ISSUE #104: [CONTINUOUS TEST] - Improve Automation Process
- After performing all the tests, can we report back the code coverage results in the PR so that we can take a look at how much of the code-base is covered by out test suites?
- Can we apply some quality gates using SonarQube to ensure the following
   - Static Code analysis passes with less number of code smells, bugs, vulnerabilities and security hotspots?
   - Code Coverage passes with a minimum percentage of Line/Branch Coverage.
- Integrate "Mutation Testing" in out continuous testing automation process? Sometimes Code coverage are not enough to ensure the quality of our test code. Mutation tests can ensure us we have a quality test suite that fails whenever any changes is done in the app code. Also let's put a quality gate on this as well.

### PR DESCRIPTION
**Pull request by Catalin-Andronie**
Closes #104

- [x] Collect code coverage
- [ ] Generage coverage summary as a Pull Request comment

### CODE REVIEW

**Comment by hassanhabib** [comment]
@Catalin-Andronie why do we need code coverage?

**Comment by Catalin-Andronie** [comment]
@hassanhabib Because the team develops and tests each feature at the same time, code coverage does not bring much value. However, when reviewing PR(s), code coverage may easily surface missing test cases which leads to lower time spent in code review and a better understanding of what was missed by the contributor.

Let me know if you want me to continue enabling code coverage.

**Comment by hassanhabib** [comment]
> @hassanhabib Because the team develops and tests each feature at the same time, code coverage does not bring much value. However, when reviewing PR(s), code coverage may easily surface missing test cases which leads to lower time spent in code review and a better understanding of what was missed by the contributor.
> 
> Let me know if you want me to continue enabling code coverage.

@Catalin-Andronie can we enable code coverage only for files post-fixed by the term "Service"?

**Comment by hassanhabib** [comment]
Shutting this one down due to inactivity

**Comment by Catalin-Andronie** [comment]
@hassanhabib I am working on it. I have found a way in which we can filter the files taken into account in the code summary report.

At the moment I am struggling to make the report prettier. For that found this GitHub action <https://github.com/irongut/CodeCoverageSummary> which generates a prettier summary and unfortunately, it does not allow for file/class filtering. I am currently working on adding support for file/class filtering via this issue <https://github.com/irongut/CodeCoverageSummary/issues/150>: 

After I will finish that and then I'll create a new task in ADotNet, I will be able to continue adding code coverage to this project.

**Pull request closed without merging**
